In [1]:
import numpy as np

print(np.__version__)

2.4.6


In [2]:
arr1 = np.array([10, 20, 30, 40])

print(arr1)
print("Shape:", arr1.shape)

[10 20 30 40]
Shape: (4,)


In [3]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2)
print("Shape:", arr2.shape)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [4]:
arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(arr3)
print("Shape:", arr3.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


In [5]:
a = np.array([10, 20, 30])

print(a + 5)
print(a * 2)

[15 25 35]
[20 40 60]


In [6]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]


In [7]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(a @ b)

[[19 22]
 [43 50]]


In [8]:
data = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(data))
print("Standard Deviation:", np.std(data))

Mean: 30.0
Standard Deviation: 14.142135623730951


In [9]:
x = np.array([10, 20, 30, 40, 50])
y = np.array([15, 25, 35, 45, 55])

correlation = np.corrcoef(x, y)[0, 1]

print("Correlation:", correlation)

Correlation: 1.0


In [10]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\Anish kumar tiwari\Downloads\student_performance (1).csv")

print(df.head())

   Hours_Studied  Practice_Tests  Marks  Attendance
0              2               1     45          70
1              3               1     50          72
2              4               2     55          75
3              5               2     61          78
4              6               3     65          80


In [11]:
print(df.shape)
print(df.columns)

(10, 4)
Index(['Hours_Studied', 'Practice_Tests', 'Marks', 'Attendance'], dtype='str')


In [12]:
mean_marks = np.mean(df["Marks"])

print("Mean Marks:", mean_marks)

Mean Marks: 67.5


In [13]:
correlation = np.corrcoef(
    df["Hours_Studied"],
    df["Marks"]
)[0, 1]

print("Correlation:", correlation)

Correlation: 0.9995351809637898


In [14]:
print("Mean Marks:", np.mean(df["Marks"]))
print("Standard Deviation:", np.std(df["Marks"]))
print("Correlation:", np.corrcoef(df["Hours_Studied"], df["Marks"])[0, 1])

Mean Marks: 67.5
Standard Deviation: 14.263590010933433
Correlation: 0.9995351809637898
